### ISSUE TITLE
Expo Demo on website home page uses an outdated Expo SDK version

### ISSUE THREAD

**Issue by MeltdownInteractive** [react-native-elements/react-native-elements#3694] opened 2022-12-02 01:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

I tried to run the demo on your website.

### Expected behavior

I should be able to run your demo on a more recent version of the Expo SDK.

### Describe the bug

On https://reactnativeelements.com/ I tried to run the Expo Go demo, and it tells me it only supports the 44 SDK.
I have the 47 SDK installed, and it tells me 46 or 45 would work too, but 44 requires an older SDK version.

This is a bad UX for new users wanting to try our your demo/SDK so I'd recommend the demo on the website is updated.

### Steps To Reproduce

```Markdown
1. Scan the QR code with Expo
2. Try to run the demo
```

### Your Environment

<details>
<summary>`npx @rneui/envinfo`</summary>

      ```
        Output from `npx @rneui/envinfo` goes here.
      ```

</details>

**Comment by arpitBhalla** [comment] 2022-12-10 21:17
Duplicate of #3688 3698

**Closed as completed by arpitBhalla** 2022-12-10 21:17 UTC
Labels: Needs Triage
