### ISSUE TITLE
Add Carousel component as well 

### ISSUE THREAD

**Issue by M2Changezi** [react-native-elements/react-native-elements#3134] opened 2021-07-09 05:21 UTC
**Is your feature request related to a problem? Please Describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by arpitBhalla** [comment] 2021-07-09 05:22
Duplicate of https://github.com/react-native-elements/react-native-elements-universe/issues/4

**Comment by ShivamTyagi12345** [comment] 2021-07-10 13:27
I would like to work on this issue

**Comment by arpitBhalla** [comment] 2021-07-10 13:29
Go for it

**Comment by ShivamTyagi12345** [comment] 2021-07-13 19:54
sir i am setting up this project locally . I went through the official contributing guidelines over [HERE](https://reactnativeelements.com/docs/contributing)

Firstly , i tried **yarn install
yarn test** ,All i got was a successful check.
![Screenshot (196)](https://user-images.githubusercontent.com/60812924/125516288-cc43e5f7-5a98-44ce-9eb6-6824acc09c7d.png)

Secondly, I according to my understanding went to F:\<--->\react-native-elements\website\website and ran the command **yarn run**. I dont understand what this error is about:
![Screenshot (195)](https://user-images.githubusercontent.com/60812924/125515549-c4e341f0-5672-4238-9ec3-eead9558e81d.png)
 
Can i please have some initial help

**Comment by khushal87** [comment] 2021-07-13 20:36
Shouldn't it be 
1) cd react-native-elements/website
2) yarn start
@ShivamTyagi12345

**Comment by arpitBhalla** [comment] 2021-07-14 10:15
Hey @ShivamTyagi12345 you need to follow these steps:
1. Clone demo app repo
2. Use `tsc` to transpile the code in this repo dir and then copy it to `node_modules` of demo app repo dir.

**Comment by flyingcircle** [comment] 2021-07-15 21:31
As @arpitBhalla duplicate of the other ticket. Please discuss there.

**Closed by flyingcircle** 2021-07-15 21:31 UTC
