### ISSUE TITLE
Using ref with input and Typescript

### ISSUE THREAD

**Issue by DanJamesH** [react-native-elements/react-native-elements#3445] opened 2022-04-07 09:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

I tried to set up a ref with an Input component using Typescript.

### Expected behavior

What happens is that attempted to declare the ref using 

` const input = React.createRef<Input>();`

and using that ref in the Input component like 

`<Input
        ref={input}
/>`

### Describe the bug

I then get the error "'Input' refers to a value, but is being used as a type here. Did you mean 'typeof Input'?" which is clear enough but if I then rewrite the ref as 

` const input = React.createRef<typeof Input>();`

I get the error 
_"Type 'RefObject<FunctionComponent<InputProps> | ForwardRefExoticComponent<InputProps>>' is not assignable to type 'Ref<TextInput> | undefined'.
      Type 'RefObject<FunctionComponent<InputProps> | ForwardRefExoticComponent<InputProps>>' is not assignable to type 'RefObject<TextInput>'."_
      
Something I noticed is that if I use TextInput from react-native in the ref, I don't get any errors but then I cannot use input.current.shake() for example.

` const input = React.createRef<TextInput>();`

I am a bit new to TS but this is fairly simple use case and I was hoping that some clarity may be provided. I have seen similar issues have been logged here but there were no clear responses.

Thank you!

### Steps To Reproduce

```markdown
1. Look at example of ref Input in docs.
const input = React.createRef();

<Input
  ref={input}
  ...
/>

2. Change const input = React.createRef(); to const input = React.createRef<Input>();
```

### Your Environment

```markdown
"@rneui/base": "^4.0.0-rc.1",
"@rneui/themed": "^4.0.0-rc.1",
"@types/react-native": "~0.64.12",
"typescript": "~4.3.5",
"expo": "~44.0.0",
"react-native": "0.64.3",
```

**Comment by arpitBhalla** [comment] 2022-04-29 20:23
Duplicate of #3202

**Closed as completed by arpitBhalla** 2022-04-29 20:23 UTC
Labels: component: Input
