### ISSUE TITLE
Tsc warnings from components Input and Searchbar

### ISSUE THREAD

**Issue by khushal87** [react-native-elements/react-native-elements#2870] opened 2021-03-17 13:39 UTC
**Explain what you did (Required)**
Using Components such as Searchbar and Input with typescript brings up certain tsc errors/warning which are critical for the application. I have used `ref` as well as `placeholder` props which throw this warnings.

**Expected behavior (Required)**
The `tsc --watch` checks must run without any errors in the application which uses these components.

**Describe the bug (Required)**
Tsc warnings are coming up in the application using the components `Searchbar` and `Input`. The events which like `shake, focus etc.` face same issue.

**To Reproduce (Required)**

We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

**Screenshots (Required)**
![Capture2](https://user-images.githubusercontent.com/39884168/111476157-e5100600-8753-11eb-832a-541441a57d76.PNG)
![Capture1](https://user-images.githubusercontent.com/39884168/111476164-e6d9c980-8753-11eb-8a5f-866362e951dc.PNG)
![Capture3](https://user-images.githubusercontent.com/39884168/111476167-e93c2380-8753-11eb-9533-f20bde6dd505.PNG)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    https://github.com/react-native-elements/react-native-elements     |
| react-native          |    https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz     |

**Comment by khushal87** [comment] 2021-03-17 13:40
@flyingcircle I would like to coordinate with you to solve and get a possible fix with you. Thanks.

**Comment by akgupta0777** [comment] 2021-03-18 12:59
The pull request is merged and i think the problem is solved so we should close the issue.

**Comment by khushal87** [comment] 2021-03-18 13:00
Can you share the PR id?

**Comment by khushal87** [comment] 2021-03-18 13:07
That's in `react-native-elements-app` @akgupta0777 . I have referenced this issue here as it was coming from this package in that app. And I have mentioned there that this is a issue we need to work upon such that problem is resolved.

**Comment by akgupta0777** [comment] 2021-03-18 13:09
ohh, sorry I didn't see that.

**Comment by khushal87** [comment] 2021-03-18 13:20
No worries

**Closed** 2022-01-20 02:33 UTC
