### ISSUE TITLE
Fix Button Documentation

### ISSUE THREAD

**Issue by NathanNovak** [react-native-elements/react-native-elements#3531] opened 2022-05-17 21:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

Tried to import Button

### Expected behavior

Make documentation consistent 

### Describe the bug

On the Overview page the example in the docs the import for Button is: 
import { Button } from '@rneui/base';

The Button docs say: 
import { Button } from "@rneui/themed";

I get an error when @rneui/themed is imported but not when @rneui/base is imported

### Steps To Reproduce

```Markdown
import Button from @rneui/themed
```

### Your Environment

<details>
<summary>`npx @rneui/envinfo`</summary>

      ```
        Output from `npx @rneui/envinfo` goes here.
      ```

</details>

**Comment by arpitBhalla** [comment] 2022-05-18 02:39
Duplicate of #3519

**Closed as completed by arpitBhalla** 2022-05-18 02:39 UTC
Labels: Needs Triage
