### ISSUE TITLE
How to avoid flickering when Avatar re-render again and again.

### ISSUE THREAD

**Issue by Biplovkumar** [react-native-elements/react-native-elements#2233] opened 2020-01-06 09:49 UTC
**Explain what you did**

**Expected behavior**

 not show to user that, avatar re-render again and again.

**Describe the bug**

**To Reproduce**

                   <Avatar
                          rounded
                          size={height/6}
                          defaultSource ={DummyUser}
                          source ={profileimageTutor ? {uri:profileimage} : DummyUser} 
                          defaultSource ={profileimageTutor ? {uri:profileimage} : DummyUser} 
                          icon={{name: 'user', type:'antdesign'}}
                          containerStyle={{borderWidth:3, borderColor:Colors.Grey89, elevation:2}}
                          resizeMethod="scale"
                          resizeMode="cover"
                      />

**Screenshots**
1. ![Screenshot 2020-01-06 at 3 16 06 PM](https://user-images.githubusercontent.com/30401136/71810060-79ce9c80-3097-11ea-985e-93b4bc11153e.png)
2. ![Screenshot 2020-01-06 at 3 15 43 PM](https://user-images.githubusercontent.com/30401136/71810061-7a673300-3097-11ea-83e8-00d294d1d2f8.png)

**Your Environment (please complete the following information):**

| software              | version |
yarn install v1.16.0
| --------------------- | ------- |
 "react-native-elements": "^1.2.7",
"react": "16.9.0",
 "react-native": "0.59.9",

**Comment by xavier-villelegier** [comment] 2020-01-06 10:27
Hey @Biplovkumar 

The `Avatar` is basically just a wrapper around the `Image` component, the flickering is mostly caused by `Image`, the `Avatar` doesn't have any state refreshment that may cause this issue.

I found this comment https://github.com/facebook/react-native/issues/981#issuecomment-354767548 about how to fix this flickering on the `Image` component. The `Avatar` has an `imageProps` props that allows you to pass props directly to the `Image`.

**Comment by Biplovkumar** [comment] 2020-01-13 17:41
<Image
  style={styles.logoImage}
  resizeMethod="scale"
  resizeMode="cover"
  source={Logo}
  defaultSource={Logo} 
 />

Thanks for replying.
I had already tried this code from this issue.
But still it is flickering after set state.
It happening only in Avatar not in image components.

**Comment by Biplovkumar** [comment] 2020-01-19 15:35
Any update on Avatar issues.
It is still fluctuating after set state.

**Comment by ozerty** [comment] 2020-01-29 15:48
Hi, I got the same issue here. Any update guys ?

**Comment by raRaRa** [comment] 2020-02-13 10:02
Same issue here, only happens on iOS for me. I'm going to try to put the component into its own component wrapped with `React.memo` to see if that helps, since this seems to be related to when the component re-renders due to state changes.

**Comment by raRaRa** [comment] 2020-02-13 10:27
I can confirm that wrapping the component with React.memo solved the issue for me, since the component will be cached and not re-rendered unless the image changes.

**Comment by Cchumi** [comment] 2020-02-25 09:15
Hi same issue here how do you use React.memo ?

**Comment by raRaRa** [comment] 2020-02-25 09:34
If you have a functional component then you can export it like this:

```
const FunctionalComponent= () => {
    return (<h1>Hello world</h1>)
}

export default React.memo(FunctionalComponent)
```

This will only cause the component to re-render if any of the props have changed.

If you use class component then you can extend it from `PureComponent` instead of `Component`:

```
class ClassComponent extends React.PureComponent {
```

`PureComponent` will work like `React.memo`

**Comment by raRaRa** [comment] 2020-02-25 09:36
The permanent fix would probably be to do this internally in the Avatar component, to avoid unnecessary re-renders. Or fix whatever is causing it to flicker with each re-render. Very likely some `componentDidUpdate` or `componentWillUpdate` issue inside `Avatar`.

**Comment by xavier-villelegier** [comment] 2020-02-25 14:34
@Biplovkumar @raRaRa @Cchumi Could you guys reproduce this issue with a really simple example on https://snack.expo.io/ ? With a simple component update its state and the Avatar flickering ? I couldn't reproduce this locally

**Comment by Cchumi** [comment] 2020-02-25 16:13
I am unable to reproduce this behavior.... Other strange thing for me is :
If I use this url : https://s3.amazonaws.com/uifaces/faces/twitter/adhamdannaway/128.jpg as avatar source I have no flickering but if I use my url: https://firebasestorage.googleapis.com/v0/b/oq70-objectifquebec.appspot.com/o/users%2F0YlNi3Vn2BOqvWOVepxNyYfmjYr1%2Fprofile_pic.jpg?alt=media&token=f9072f83-55c9-4c5d-8392-77744c779171
It flicker as before...

Also I pass my component to PureComponent but it does not solve the issue.

**Comment by raRaRa** [comment] 2020-02-25 17:22
@Cchumi Then your component is re-rendering for some reason, e.g. if a prop has changed.

**Comment by Cchumi** [comment] 2020-02-25 17:39
just make a simple snack:
 This is a  simple snack with the behavior. 
[https://snack.expo.io/@cchumi/avatar-flicker](url)

**Comment by Cchumi** [comment] 2020-02-26 08:04
@xavier-villelegier find out what causing this on ios only. React native on ios only has a cache property. In avatar component it's like it is set to reload.

**Comment by xavier-villelegier** [comment] 2020-02-26 13:20
@ozerty Oh okay I see ! If you manage to fix this by changing something in the `Avatar` feel free to let us know / submit a PR !

**Comment by ozerty** [comment] 2020-02-26 14:06
@xavier-villelegier I think your message was destinated to @Cchumi 
Thanks guys

**Comment by ozerty** [comment] 2020-02-26 14:08
Just to let you know, I fix this issue by doing memoization on my avatar component.

**Comment by Cchumi** [comment] 2020-02-26 15:41
@xavier-villelegier I try but cannot get a fix... cache settings is not a good idea.

**Comment by rob5408** [comment] 2020-03-02 21:52
@ozerty Mind sharing your memoization approach? I tried that a while ago and it didn't fix the flickering. But I probably did something dumb.

**Comment by ozerty** [comment] 2020-03-03 20:36
@rob5408 Using React functional component :

`const myAvatar = useMemo(() => {
    return (
      <Avatar
        ...props
      />
    );
  }, [...]);`

And then in my render : 

`<View>{myAvatar}</View>`

Hope it will help some of you.

**Comment by Biplovkumar** [comment] 2020-03-04 17:56
It's not the solution.
Plz fix it in next release.
It should never be flicker.
It's a big bug of Avatar.
I love react native elements so I am waiting for fix in next release.

**Comment by ozerty** [comment] 2020-03-04 18:04
@Biplovkumar I agree.

**Comment by xavier-villelegier** [comment] 2020-03-04 19:07
Hey guys @Biplovkumar @ozerty @Cchumi 

Could you please use the branch `issue-2233-fix-avatar-flicker` and tell me if it's fixed ?

You can do adding this to your `package.json`
```
"react-native-elements": "https://github.com/react-native-elements/react-native-elements#issue-2233-fix-avatar-flicker",
```

It works for me

**Comment by ozerty** [comment] 2020-03-04 21:21
@xavier-villelegier Well done ! It's fixed for me.
thanks

**Comment by Biplovkumar** [comment] 2020-03-05 04:57
@xavier-villelegier  Nice.
it's working.
I hope it should be the same in the next release.

**Comment by Cchumi** [comment] 2020-03-05 06:26
Works for me too but it breaks the input component on input field. It just don’t show my inputcomponent. When I reverted back to latest 1.2.7 everything works

**Comment by xavier-villelegier** [comment] 2020-03-05 08:59
@Cchumi We changed to `InputComponent` with a capital in the `next` release to follow React/React Native (component props should be capitalized)

**Comment by Cchumi** [comment] 2020-03-09 06:20
@xavier-villelegier Thanks for your answer :). I didn't see that

**Comment by tkoolreact** [comment] 2020-03-15 15:30
I got far less flickering using (issue-2233-fix-avatar-flicker), mostly gone, but then it seemed to break the width and height property of the Overlay component. These props were then not being honored (or couldn't be set). Reverted back to 1.2.7. Hopefully will be fixed in the next update.

**Comment by ugrdursun** [comment] 2020-04-24 12:43
> Hey guys @Biplovkumar @ozerty @Cchumi
> 
> Could you please use the branch `issue-2233-fix-avatar-flicker` and tell me if it's fixed ?
> 
> You can test by adding this to your `package.json`
> 
> ```
> "react-native-elements": "https://github.com/react-native-elements/react-native-elements#issue-2233-fix-avatar-flicker",
> ```
> 
> It works for me



> Hey guys @Biplovkumar @ozerty @Cchumi
> 
> Could you please use the branch `issue-2233-fix-avatar-flicker` and tell me if it's fixed ?
> 
> You can test by adding this to your `package.json`
> 
> ```
> "react-native-elements": "https://github.com/react-native-elements/react-native-elements#issue-2233-fix-avatar-flicker",
> ```
> 
> It works for me

this did not work on me still same, should i clear some cache or something ? or install that package to react-native-elements directory ? what did i do wrong ?

**Comment by flyingcircle** [comment] 2020-05-07 05:02
Will be released in 2.0.1

**Closed by flyingcircle** 2020-05-07 05:02 UTC
Labels: :boom:  Bug

**Comment by lambdadev007** [comment] 2021-04-28 07:45
I know the answer is late, but posting my answer here in case someone still want to find a solution and because I've found this drives some traffic. A simple workaround is to add a css transition property to the image like the below:

`transition: all 2s;`

it does not prevent the image re-rendering, but at least it does prevent image flickering.

**Comment by olegderecha** [comment] 2021-08-30 15:34
Tried to resolve the issue, but found that `react-native-elements` version was too old `2.0.0`, updated to `3.4.2`, and now it works much better!

**Comment by Amitkumarttn** [comment] 2022-04-14 05:04
<Image
        source={isAndroid ? require('../../avatar.png') : null}
        style={styles.imageStyle}
        resizeMode='cover'
        resizeMethod="scale"
        defaultSource={isAndroid ? null : require('../../avatar.png')}
      />

**Comment by Amitkumarttn** [comment] 2022-04-14 05:04
`<Image
source={isAndroid ? require('../../avatar.png') : null}
style={styles.imageStyle}
resizeMode='cover'
resizeMethod="scale"
defaultSource={isAndroid ? null : require('../../avatar.png')}
/>`

**Comment by amitkumarcoding** [comment] 2022-04-14 05:06
`<Image
        source={isAndroid ? require('avatar.png') : null}
        style={styles.imageStyle}
        resizeMode='cover'
        resizeMethod="scale"
        defaultSource={isAndroid ? null : require('avatar.png')}
      />`

**Comment by learncodingforweb** [comment] 2023-06-15 18:20
I am also facing flicker image of base64 data from websocket. Can someone help me

**Comment by Suzan-Dev** [comment] 2023-09-10 07:20
using `ignoreFallback` prop worked for me

**Comment by alirazzaq-dev** [comment] 2024-06-03 01:51
memo didn't work but using ignoreFallback prop worked for me as well. Thanks.
