### ISSUE TITLE
None of the press events work on ListItem.Swipeable

### ISSUE THREAD

**Issue by ikiK-CRO** [react-native-elements/react-native-elements#3218] opened 2021-10-10 13:24 UTC
I tried to implement this in numerous ways. Nothing works. I have also tried to tye press events on items itself also 0 effects. 

None of the onLongPress or onPress works anywhere, not on ListItem.CheckBox or on items in the list. As you can see I even tried with Pressable. 0 effect.

What am I doing wrong?   I see nothing about Swipeable not being able to receive these events in the documentation.

Also while I'm at it, implementing scroll view with Swipeable is not working properly, I had to add padding on sides to be able to scroll list on edges. I searched for answers everywhere. How can I control swiping and scroll actions of ListItem.Swipeable? 

```
{items.map((l, i) => (
              <ListItem.Swipeable
                key={l.id}
                bottomDivider
                rightContent={
                  <Button
                    title='VIŠE'
                    icon={{ name: 'menu-open', color: 'white' }}
                    buttonStyle={{
                      minHeight: '100%',
                      backgroundColor: GLOBAL.ALTCOLOR
                    }}
                    // onPress={() => toggleModal(l, 'modal1')}
                  />
                }
                leftContent={
                  <Button
                    title='OBRIŠI'
                    icon={{ name: 'delete', color: 'white' }}
                    buttonStyle={{
                      minHeight: '100%',
                      backgroundColor: 'red'
                    }}
                    // onPress={() => addMore(l.value)}
                  />
                }
              >
                {/* <Icon
                  name='clipboard'
                  size={20}
                  iconStyle={{ margin: 0, padding: 0 }}
                /> */}
                {/* <Pressable onPress={() => HandleCheckBoxPress(l)}> */}
                <ListItem.CheckBox
                  iconType='material'
                  checkedIcon='check-box'
                  uncheckedIcon='check-box-outline-blank'
                  checkedColor={GLOBAL.ALT2COLOR}
                  checked={l.checked}
                  // onIconPress={() => HandleCheckBoxPress(l)}
                  // onPress={() => HandleCheckBoxPress(l)}
                  onPress={() => console.log(true)}
                  center={true}
                />
                {/* </Pressable> */}
                <ListItem.Content>
                  <ListItem.Subtitle style={{ fontWeight: 'bold' }}>
                    <Badge
                      value={l.values.length}
                      status='success'
                      badgeStyle={{
                        marginTop: 0,
                        marginRight: 7,
                        padding: 0,
                        backgroundColor: GLOBAL.MAINCOLOR
                      }}
                    />
                    {l.time}
                  </ListItem.Subtitle>
                </ListItem.Content>
                <ListItem.Chevron />
              </ListItem.Swipeable>
```

**Comment by NoahFace** [comment] 2021-11-18 20:33
Touches on ListItem.Swipeable fire onPress + onPressIn + onPressOut events.

You should generally use onPress, but this is broken on Android. I think the issue is that on Android the scrolling and swiping are too sensitive, so if you move your finger a minute amount between the in and out, it will think you are swiping or scrolling and onPress won't fire.

You can use onPressIn as suggested, but this will mean that if you want to swipe or scroll, then the list item will also be pressed (which you probably don't want). So, if you are going to do this, I suggest making it conditional on android so the IOS version works as it should.

Also, I don't think it is possible to get onLongPress to fire on Android at all.

A fix or workaround is desperately needed for Android. Any ideas?

**Comment by NoahFace** [comment] 2021-11-18 20:47
BTW, the issue only happens on a physical Android device. When you click with a mouse in the Simulator, the In/Out happen at the same location, therefore the press event will always fire.

**Comment by cristeacosmin** [comment] 2021-12-19 12:00
I can confirm this happens on iOS physical device as well

**Comment by NoahFace** [comment] 2022-02-03 07:16
@arpitBhalla really hoping you manage to fix this - I can see you have it tagged to 4.0. 
I will certainly be testing the 4.0 beta once it is fixed.

**Comment by NoahFace** [comment] 2022-04-08 01:32
@arpitBhalla I can see this is 1 of only 8 issues tagged to 4.0 that have not yet been addressed.
I really need a fix for this issue - is there anything I can do to assist?

**Comment by arpitBhalla** [comment] 2022-04-09 09:00
Hey @NoahFace Can you try if it's working now, Use
```bash
yarn add arpitbhalla/react-native-elements#base

yarn add arpitbhalla/react-native-elements#themed
```

**Comment by NoahFace** [comment] 2022-04-09 21:13
@arpitBhalla 
In my initial testing this change seems to be working!
I will run some more complete regression testing and report back again ASAP.

**Comment by ikiK-CRO** [comment] 2022-04-09 21:15
Oh my good guys or gilrs if you fix this, ill kiss you all on the forehead... 

Btw sorry for not mentioning this before, but I see some talk about the version, I'm having these problems on 3.4.2, if that means anything (it was the latest version when making this post).

**Comment by NoahFace** [comment] 2022-04-09 22:19
@ikiK-CRO 
You are going to have to upgrade to 4.0.0 to get this fix, unless you want to try to back-port it yourself.
Upgrading should just be installing the two new packages and changing your imports to something like the following:

import { Icon, ListItem, Button } from '@rneui/base'

**Comment by ikiK-CRO** [comment] 2022-04-09 22:50
I'm willing to try if it's doable, this fix would greatly improve my current page in RN... Also, I could in the future use it in more ways, And I kind of have plenty going on on that page, as it wouldn't be limited... This is a pretty big issue with Swipeable now that I think on it again...

Looking forward to any possible fixes, and I'm sorry that my limited knowledge is not of help...

**Comment by NoahFace** [comment] 2022-04-09 23:09
@arpitBhalla this change appears to be all good.
The onPress and onLongPress events are now responding as they should both on Android and iOS devices.
I've also verified that the existing behaviour (eg: scrolling, swiping with buttons, etc) continues to work as it should.
Please commit this through to the stable build and final 4.0 release.

Your work on this is GREATLY appreciated!

**Closed** 2022-04-27 18:53 UTC
Labels: :bug: Bug, component: ListItem, priority: high
