### ISSUE TITLE
Fix all @ts-ignore tags

### ISSUE THREAD

**Issue by flyingcircle** [react-native-elements/react-native-elements#2798] opened 2021-03-07 22:00 UTC
In order to convert over to typescript there were some particularly difficult issues that weren't able to be resolved without using @ts-ignore. Resolve all remaining @ts-ignore tags.

- [x] index.ts
- [x] Accessory
- [x] Avatar
- [x] Button
- [x] ButtonGroup
- [x] Card - subcomponents
- [x] Checkbox
- [x] ThemeProvider
- [x] withTheme
- [x] Header
- [x] Icon
- [x] Image
- [x] Input
- [x] Pricing
- [ ] Searchbars
- [x] SocialIcon
- [x] FeaturedTile
- [x] Tile
- [x] Tooltip

**Comment by nlok5923** [comment] 2021-03-10 02:03
@flyingcircle i want to work on this issue but please can you explain me a bit more about this issue as i am new to this project.

**Comment by flyingcircle** [comment] 2021-03-10 02:38
Yeah, so I recently converted the library to using TypeScript. However, in order to have everything compile, I had to add `// @ts-ignore` to different lines. This tag means that the typescript compiler ignores the line directly below it. 

So the goal here is to delete every instance of `@ts-ignore` and fix the typescript error that it is hiding.

**Comment by nlok5923** [comment] 2021-03-10 02:40
@flyingcircle sir can you please assign this issue to me so that i can create a pr for resolving this issue,

**Comment by nlok5923** [comment] 2021-03-10 03:14
@flyingcircle sir please can you let me know how can i compile package .

**Comment by arpitBhalla** [comment] 2021-03-11 18:08
@pranshuchittora May I work on this?

**Comment by nlok5923** [comment] 2021-03-12 00:02
@arpitBhalla thanks for asking but currently I am working on it so please you may find another one.

**Comment by flyingcircle** [comment] 2021-03-12 00:11
@arpitBhalla  yes, just say which component you're working on. There's lots of work here, so plenty of room for multiple people to work on it.

**Comment by flyingcircle** [comment] 2021-03-12 00:12
I cleared the assignees from this ticket because it is quite large and easily divided into smaller tasks. Please state which component's ignore tags you're going to work on as I have them listed above so that no one works on top of each other.

**Comment by nlok5923** [comment] 2021-03-12 00:39
@flyingcircle i had removed //@ts-ignore from accessory component as currently removing it returns not error.

**Comment by flyingcircle** [comment] 2021-03-12 03:04
@nlok5923 well, actually the error was being hidden because of an issue in `withTheme`. I pushed the fix so hopefully nothing is hidden anymore. But the fix in `withTheme` also ended up fixing `Accessory` as well.

**Comment by sarthakm21** [comment] 2021-03-12 06:13
@flyingcircle I would like to work on the button component

**Comment by arpitBhalla** [comment] 2021-03-12 06:22
@flyingcircle  I am working on Button

**Comment by nlok5923** [comment] 2021-03-12 07:26
@flyingcircle i am working on header component.

**Comment by bhanujggandhi** [comment] 2021-03-12 15:38
I am working on SearchBar and CheckBox

**Comment by arpitBhalla** [comment] 2021-03-12 15:42
@bhanujggandhi I have done Checkbox 😊

**Comment by bhanujggandhi** [comment] 2021-03-12 16:01
> @bhanujggandhi I have done Checkbox , you can do input and search bar, both are similar

@arpitBhalla  Sure!

**Comment by flyingcircle** [comment] 2021-03-13 18:03
All: I will not accept the use of `as any`. Using `any` in typescript generally means that you are ignoring the type and it is considered bad practice to use `any`. So these solutions are not actually solving anything. When you are fixing the @ts-ignore, I will not accept any use of `any`

**Comment by sarthakpranesh** [comment] 2021-03-14 18:25
Hey, I am working on ThemeProvider. I made the required changes but two of the snapshot tests are failing namely from the components `Header` and `BottomSheet`. My changes as well as the error are attached below:
ThemeProvider (only updated portion):
```ts
export const ThemeContext: React.Context<ThemeProps<{}>> = React.createContext<
  ThemeProps<{}>
>({
  theme: {
    colors,
  },
  updateTheme: () => {},
  replaceTheme: () => {},
});
```
![image](https://user-images.githubusercontent.com/41206172/111079429-ff619e00-851f-11eb-8956-9671a1bb4142.png)

Also, `yarn test` before making any changes still gave the snapshot error from the `Header` component. Please let me know if I am doing something wrong and what's required here. Thanks in advance :rocket:

**Comment by k-guy-dev** [comment] 2021-03-22 09:08
Hi @flyingcircle ! I've made a PR for the Image component, @ts-ignore is resolved and the component has been migrated to functional component. Although for some reason the Avatar and Tile components are failing tests. Please can you help me in figuring out what might be the cause.

**Closed** 2021-03-28 16:22 UTC
Labels: $100-bounty
