### ISSUE TITLE
display errors after running expo start --web

### ISSUE THREAD

**Issue by fbryo21** [react-native-elements/react-native-elements#3619] opened 2022-08-25 03:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

I cannot running the app with expo start --web, after I install with running ```npm install @rneui/themed @rneui/base``` & 
install peer dependencies

### Expected behavior

Successfully run the app

### Describe the bug

the bug displays ```You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders```      

### Steps To Reproduce

```Markdown
1. run  install @rneui/themed @rneui/base & install peer dependencies
2. run ```expo start --web```
```

### Screenshots

![Screenshot 2022-08-25 103953](https://user-images.githubusercontent.com/36603375/186569386-63a5ca22-10cd-4d47-ae25-3a77d8f08001.png)

### Your Environment

<details>
<summary>`npx @rneui/envinfo`</summary>

      ```
        Output from `npx @rneui/envinfo` goes here.
      ```

</details>

**Comment by arpitBhalla** [comment] 2022-09-21 16:26
Duplicate of #3607

**Closed as completed** 2022-09-21 16:26 UTC
Labels: Needs Triage
