### ISSUE TITLE
Tooltip: popover move elements when appears

### ISSUE THREAD

**Issue by adrxlm** [react-native-elements/react-native-elements#2301] opened 2020-03-19 05:18 UTC
version: **"^1.2.7"**,
Device: Android

I want to create a Header component with an icon that shows the popover

**Expected behavior**

The Tooltip component shows popover without moving its children element

**Describe the bug**

It could be reproduced using Avatar, Icon and Text element

**Screenshots**

Avatar

![Peek 2020-03-19 01-27](https://user-images.githubusercontent.com/307919/77033973-68531c00-6987-11ea-912c-950aa97c9004.gif)

```
import React from 'react';
import { Text } from 'react-native';

// theme
import { Header, Icon, Tooltip, Avatar } from 'components';

const App: () => React$Node = () => {
  return (
    <Header
      rightComponent={() => (
        <Tooltip popover={<Text>Info here</Text>} overlayColor="transparent">
          <Avatar rounded icon={{ name: 'person' }} />
        </Tooltip>
      )}
    />
  );
};

export default App;
```

Icon

![Peek 2020-03-19 01-27-2](https://user-images.githubusercontent.com/307919/77033834-0e525680-6987-11ea-830d-2e39b72bfb5e.gif)

```
import React from 'react';
import { Text } from 'react-native';

// theme
import { Header, Icon, Tooltip, Avatar } from 'components';

const App: () => React$Node = () => {
  return (
    <Header
      rightComponent={() => (
        <Tooltip popover={<Text>Info here</Text>} overlayColor="transparent">
          <Icon name="person" />
        </Tooltip>
      )}
    />
  );
};

export default App;
```

Text

![Peek 2020-03-19 02-08-4](https://user-images.githubusercontent.com/307919/77033691-b61b5480-6986-11ea-951b-9d6ca4f438fb.gif)

```
const App: () => React$Node = () => {
  return (
    <Header
      rightComponent={() => (
        <Tooltip popover={<Text>Info here</Text>} overlayColor="transparent">
          <Text>Info here</Text>
        </Tooltip>
      )}
    />
  );
};
```

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    ^1.2.7     |
| react-native          |    0.61.5     |

**Comment by jitish2** [comment] 2020-04-02 16:13
Any Update ? How to resolve this issue. It's coming in Android only.

**Comment by oxyii** [comment] 2020-04-04 23:42
Hey! Will be fixed in [2.0](https://github.com/react-native-elements/react-native-elements/releases/tag/untagged-755114d62e14ea50b101).

Here is [PR](https://github.com/react-native-elements/react-native-elements/pull/1875)

You can try to use my workaround for now: https://github.com/react-native-elements/react-native-elements/issues/1871#issuecomment-485255900

**Comment by guest095** [comment] 2020-04-10 07:14
> version: **"^1.2.7"**,
> Device: Android
> 
> I want to create a Header component with an icon that shows the popover
> 
> **Expected behavior**
> 
> The Tooltip component shows popover without moving its children element
> 
> **Describe the bug**
> 
> It could be reproduced using Avatar, Icon and Text element
> 
> **Screenshots**
> 
> Avatar
> 
> ![Peek 2020-03-19 01-27](https://user-images.githubusercontent.com/307919/77033973-68531c00-6987-11ea-912c-950aa97c9004.gif)
> 
> ```
> import React from 'react';
> import { Text } from 'react-native';
> 
> // theme
> import { Header, Icon, Tooltip, Avatar } from 'components';
> 
> const App: () => React$Node = () => {
>   return (
>     <Header
>       rightComponent={() => (
>         <Tooltip popover={<Text>Info here</Text>} overlayColor="transparent">
>           <Avatar rounded icon={{ name: 'person' }} />
>         </Tooltip>
>       )}
>     />
>   );
> };
> 
> export default App;
> ```
> 
> Icon
> 
> ![Peek 2020-03-19 01-27-2](https://user-images.githubusercontent.com/307919/77033834-0e525680-6987-11ea-830d-2e39b72bfb5e.gif)
> 
> ```
> import React from 'react';
> import { Text } from 'react-native';
> 
> // theme
> import { Header, Icon, Tooltip, Avatar } from 'components';
> 
> const App: () => React$Node = () => {
>   return (
>     <Header
>       rightComponent={() => (
>         <Tooltip popover={<Text>Info here</Text>} overlayColor="transparent">
>           <Icon name="person" />
>         </Tooltip>
>       )}
>     />
>   );
> };
> 
> export default App;
> ```
> 
> Text
> 
> ![Peek 2020-03-19 02-08-4](https://user-images.githubusercontent.com/307919/77033691-b61b5480-6986-11ea-951b-9d6ca4f438fb.gif)
> 
> ```
> const App: () => React$Node = () => {
>   return (
>     <Header
>       rightComponent={() => (
>         <Tooltip popover={<Text>Info here</Text>} overlayColor="transparent">
>           <Text>Info here</Text>
>         </Tooltip>
>       )}
>     />
>   );
> };
> ```
> 
> **Your Environment (please complete the following information):**
> 
> software	version
> react-native-elements	
> react-native

Go src->Tooltip->Tooltip.js and in getElementPosition() method remove StatusBar.currentHeight from yOffset

**Comment by adrxlm** [comment] 2020-04-10 15:33
But what about to release a patch for the current version? We don't know when version 2.0 will release.

**Comment by flyingcircle** [comment] 2020-04-26 23:29
@adrxlm Double checked that this will be fixed in 2.0.0. We should be releasing this week. (Next week at latest.

**Closed by flyingcircle** 2020-04-26 23:29 UTC

**Comment by cnmmbd** [comment] 2020-05-07 13:36
hi, I have updated to 2.0.0, and I found that this still happened while using tooltip within a Tab.Screen of react-navigation.
`export default function App() {
    return (
        <NavigationContainer>
            <Tab.Navigator 
                screenOptions={({route})=>({
                    tabBarIcon:({focused,color,size})=>{
                        let iconName;
                        if(route.name==="Home") {
                            iconName=focused
                                ?"ios-information-circle"
                                :"ios-information-circle-outline";
                        } else if(route.name==="Settings") {
                            iconName=focused
                                ?"ios-list-box"
                                :"ios-list";
                        }

                        return <Ionicons name={iconName} color={color} size={size} />
                    }
                    
                })}

                tabBarOptions={{
                    activeTintColor:"#4f467e",
                    inactiveTintColor:"gray"
                }}

            >
                <Tab.Screen name="Home" component={HomeScreen} />
                <Tab.Screen name="Settings" component={SettingsScreen} />
            </Tab.Navigator>
        </NavigationContainer>
    );
}`

**Comment by flyingcircle** [comment] 2020-05-07 14:22
@cnmmbd https://react-native-elements.github.io/react-native-elements/docs/next/tooltip.html#skipandroidstatusbar

**Comment by sepehrhh** [comment] 2020-05-08 08:25
> hi, I have updated to 2.0.0, and I found that this still happened while using tooltip within a Tab.Screen of react-navigation.
> 
> export default function App() {
> return (
> 
> <Tab.Navigator
> screenOptions={({route})=>({
> tabBarIcon:({focused,color,size})=>{
> let iconName;
> if(route.name==="Home") {
> iconName=focused
> ?"ios-information-circle"
> :"ios-information-circle-outline";
> } else if(route.name==="Settings") {
> iconName=focused
> ?"ios-list-box"
> :"ios-list";
> }
> 
> ```
>                     return <Ionicons name={iconName} color={color} size={size} />
>                 }
>                 
>             })}
> 
>             tabBarOptions={{
>                 activeTintColor:"#4f467e",
>                 inactiveTintColor:"gray"
>             }}
> 
>         >
>             <Tab.Screen name="Home" component={PlayerScreen} />
>             <Tab.Screen name="Settings" component={SettingsScreen} />
>         </Tab.Navigator>
>     </NavigationContainer>
> );
> ```
> 
> }

Same problem here. Using with react-native-navigation screen. Also think the problem is with screen top bar which height is not added to StatusBar height.

**Comment by lazarporter** [comment] 2020-06-10 23:02
@sepehrhh I am having the same issue with react-native-navigation, were you able to find a solution?

**Comment by sepehrhh** [comment] 2020-06-21 14:04
> @sepehrhh I am having the same issue with react-native-navigation, were you able to find a solution?

Unfortunately not. Waiting for an update.

**Comment by hyunminyoo** [comment] 2021-09-01 06:08
Use skipAndroidStatusBar={true}

**Comment by Ashutosh-Tiwari** [comment] 2022-02-18 06:09
https://github.com/react-native-elements/react-native-elements/issues/1871
The issue still remains. When the Modal is not used, the skipAndroidStatusBar makes no difference.
