### ISSUE TITLE
React 0.63.2 throwing Warning: Failed prop type: Invalid prop `color` supplied to `Text`: hsl(...)

### ISSUE THREAD

**Issue by naishe** [react-native-elements/react-native-elements#2466] opened 2020-07-31 08:41 UTC
**Explain what you did**
Upgraded React Native version from 0.62.2 to 0.63.2

**Expected behavior**
A button with a secondary background and primary color text

**Describe the bug**
The latest version of React Native seems to throw warning when a `Button` is added. The warning goes as follows:

```
[Fri Jul 31 2020 13:12:22.456]  ERROR    Warning: Failed prop type: Invalid prop `color` supplied to `Text`: hsl(208, 8%, 63%)
Valid color formats are
  - '#f0f' (#rgb)
  - '#f0fc' (#rgba)
  - '#ff00ff' (#rrggbb)
  - '#ff00ff00' (#rrggbbaa)
  - 'rgb(255, 255, 255)'
  - 'rgba(255, 255, 255, 1.0)'
  - 'hsl(360, 100%, 100%)'
  - 'hsla(360, 100%, 100%, 1.0)'
  - 'transparent'
  - 'red'
  - 0xff00ff00 (0xrrggbbaa)

Bad object: {
  "color": {
    "model": "hsl",
    "color": [
      208,
      8,
      63
    ],
    "valpha": 1
  },
  "fontSize": 16,
  "textAlign": "center",
  "paddingTop": 2,
  "paddingBottom": 1,
  "fontFamily": "Poppins-Light"
}
    in Text (at Button.js:145)
    in Button (at withTheme.js:40)
    in ThemedComponent (at withTheme.js:57)
    in ForwardRef(Themed.Button) (at Btn.tsx:18)
    in Btn (at LoginPanel.tsx:83)
[-- redacted for brevity --]
```

**To Reproduce**
1. Setup a React Native 0.63.2 project
2. Set a theme with a primary and secondary color
3. Add a regular `Button`
4. Load the app it in an Android emulator

**Screenshots**
| software              | version |
| --------------------- | ------- |
| react-native-elements |    ^2.0.4     |
| react-native          |    0.63.2     |

**Comment by dcboy** [comment] 2020-07-31 12:42
this issues is the same for me~~~

**Comment by flyingcircle** [comment] 2020-07-31 15:13
Duplicate of #2440 already fixed on `next` branch

**Closed by flyingcircle** 2020-07-31 15:13 UTC
