### ISSUE TITLE
Disabled button title color should default to titleStyle.color

### ISSUE THREAD

**Issue by Nantris** [react-native-elements/react-native-elements#3768] opened 2023-03-23 20:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

Failing to define a `disabledTitleStyle.color` leads to the text having either no color or the same color as the `disabledStyle.backgroundColor`

### Expected behavior

`disabledTitleStyle.color` should default to `titleStyle.color` instead of transparency when no `disabledTitleStyle.color` is explicitly defined

### Describe the bug

Disabled buttons' text is not visible
![image](https://user-images.githubusercontent.com/6835891/227356673-7f992098-a357-4d38-96e8-9cb2d1af6110.png)

**After defining `disabledTitleStyle.color**

![image](https://user-images.githubusercontent.com/6835891/227356807-8b996864-ea2a-41f2-9939-8583c61aaed2.png)

### Steps To Reproduce

```Markdown
Disable a button without explicitly defining a `disabledTitleStyle.color`
```

### Your Environment

<details>
<summary>`npx @rneui/envinfo`</summary>

      ```
React Native Elements Env Info

## Global Dependencies:

 - expo-cli : 6.3.2

## Local Dependencies:

 - @rneui/base : ~4.0.0-rc.7
 - @rneui/themed : ~4.0.0-rc.7
 - expo : ~47.0.13
 - react : ~18.1.0
 - react-native : 0.70.5

      ```

</details>

**Comment by prabhatdubey670** [comment] 2023-04-02 07:04
I can fix this issue !

**Comment by khushal87** [comment] 2023-06-10 11:38
Hey @Slapbox, are you using this code to disable the button?

```tsx
<Button disabled>Disabled</Button>
```

**Comment by Nantris** [comment] 2023-06-10 22:54
Hey @khushal87; we're using a boolean to set disabled, but otherwise the same idea:

```js
<Button disabled={bool}>Disabled</Button>
```

**Comment by khushal87** [comment] 2023-08-26 16:32
Not able to reproduce the issue in a simple button with disabled true. Not sure how are you getting this. Can you provide a code snippet? Thanks. 😄 
<img width="241" alt="Screenshot 2023-08-26 at 9 30 47 PM" src="https://github.com/react-native-elements/react-native-elements/assets/39884168/2b32f46c-c041-4598-8cc5-92c3980ce9b5">

**Comment by Nantris** [comment] 2023-08-26 18:07
@khushal87 thanks for investigating this. Did you test on the same version of RNE (4.0.0-rc.7)? 

It's possible it's been fixed. It's been 5 months now and I don't remember enough to provide more code, but felt confident at the time that the code I shared was sufficient to reproduce the problem.

**Comment by khushal87** [comment] 2023-08-27 05:39
I was testing the latest version of the package. Anyway, since I am not able to reproduce this issue, I will be closing it. If there are any updates please feel free to re-open it. Thanks for your info. 😄

**Closed as completed by khushal87** 2023-08-27 05:39 UTC
Labels: Needs Triage
