### ISSUE TITLE
keyboard is not opening in iOS 13.2.0 if i use "secureTextEntry={true}" in Input tag.

### ISSUE THREAD

**Issue by akashnsmahaswami** [react-native-elements/react-native-elements#2229] opened 2020-01-03 12:13 UTC
If i set **secureTextEntry={true}** then onFocus of input field keyboard is not popped out in iOS 13.2.0. Same code is working fine in iOS version lesser than 13.2.0.

**my code**
<Input
      placeholderTextColor="grey"
      textContentType="password"
      clearButtonMode="while-editing"
      autoCapitalize="none"
      autoCorrect={false}
      underlineColorAndroid="transparent"
      editable={true}
      placeholder="Please enter your password"
      enablesReturnKeyAutomatically
      returnKeyType="go"
      ref={ref => (this.passwordInput = ref)}
      onChangeText={password => this.setState({ password })}
      value={this.state.password}
      secureTextEntry={true}
/>

**Environment**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    1.2.7    |
| react-native          |  0.59.10  |
| iOS |    13.2.0    |
| phone |    iPhone 11    |

**Comment by emmanuel-ma** [comment] 2020-02-10 21:09
I am having the same issue on my BrowserStack iPhone 11 emulators, on my local emulators is working fine. Likely, it is just happening in real devices.

```javascript
        <Input
            containerStyle={styles.containerStyleInputControl}
            leftIconContainerStyle={styles.leftIconContainerInputControl}
            inputContainerStyle={styles.inputContainerStyleInputControl}
            inputStyle={styles.inputStyleInputControl}
            leftIcon={{
              ...iconProps,
              name: 'lock'
            }}
            secureTextEntry
            autoCompleteType="password"
            textContentType="password"
            placeholder="Password"
            placeholderTextColor="rgba(0,0,0,.15)"
            value={password}
            onChangeText={text => inputOnChange('password', text)}
            errorMessage={inputError.password}
          />
```

- react-native-elements 1.2.7
- react-native 0.61.2
- iOS 13
- iPhone 11, 11 Pro, 11 Pro Max

**Comment by emmanuel-ma** [comment] 2020-02-12 00:04
Nevermind, I think the issue is not related with this library, I just realized that it also exists with the TextInput component of react-native library.

**Comment by iRoachie** [comment] 2020-03-02 03:31
Closing as this is an upstream issue. Non-actionable by us

**Closed by iRoachie** 2020-03-02 03:31 UTC
Labels: Upstream
