### ISSUE TITLE
Typescript errors in Icon, Input, ListItem components

### ISSUE THREAD

**Issue by andkom** [react-native-elements/react-native-elements#3231] opened 2021-10-23 10:04 UTC
**Explain what you did (Required)**

After upgrading react-native i can see typescript errors in existing code

Icon: Property 'tvParallaxProperties' is missing in type...
Input: Property 'autoCompleteType' is missing in type...
ListItem: Type ... is missing the following properties from type ...: hasTVPreferredFocus, tvParallaxProperties
ListItem.Chevron: Property 'tvParallaxProperties' is missing in type '{}' but required in type ...

**Expected behavior (Required)**

No typescript errors.

**Describe the bug (Required)**

**To Reproduce (Required)**

We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

**Screenshots (Required)**

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   3.4.2      |
| react-native          |  0.66.1       |

**Comment by jkoutavas** [comment] 2021-11-01 11:46
Would love to see a resolution or work around for this.

**Comment by cbotsikas** [comment] 2021-11-01 18:45
I also have the same issue with `hasTVPreferredFocus`, `tvParallaxProperties` and `autoCompleteType`

lib | version
-- | --
react-native-elements | 3.4.2
@types/react-native | 0.66.1
react-native | 0.66.1

On a `ListItem` from `react-native-elements`:
```
error TS2739: Type '{ children: Element[]; containerStyle: { alignContent: "space-around"; alignItems: "stretch"; backgroundColor: string; borderColor: string; borderRadius: number; borderWidth: number; flex: number; flexDirection: "column"; paddingHorizontal: number; paddingVertical: number; }; }' is missing the following properties from type 'Pick<TouchableHighlightProps & { containerStyle?: StyleProp<ViewStyle>; disabledStyle?: StyleProp<ViewStyle>; ... 6 more ...; children?: any; } & Partial<...>, "testID" | ... 45 more ... | "bottomDivider">': hasTVPreferredFocus, tvParallaxProperties
```

On an `Input` from `react-native-elements`
```
error TS2741: Property 'autoCompleteType' is missing in type '{ value: string | undefined; placeholderTextColor: string; inputStyle: { fontWeight: "bold"; color: string; fontSize: number; paddingLeft: number; }; placeholder: string; leftIcon: Element; containerStyle: { ...; }; inputContainerStyle: { ...; }; onChangeText: (inputValue: string) => void; }' but required in type 'Pick<TextInputProps & RefAttributes<TextInput> & { containerStyle?: StyleProp<ViewStyle>; disabled?: boolean | undefined; ... 14 more ...; renderErrorMessage?: boolean | undefined; } & Partial<...>, "testID" | ... 125 more ... | "renderErrorMessage">'.
```

**Comment by jkoutavas** [comment] 2021-11-25 18:38
I'm seeing this in RN 0.66.3 + react-native-elements 3.4.2 as well. Can we please get a solution together?

```ts
$ npx tsc
[redacted].tsx:38:10 - error TS2741: Property 'tvParallaxProperties' is missing in type '{ color: string; }' but required in type 'Pick<Partial<IconProps> & Partial<ThemeProps<Partial<IconProps>>>, "style" | "allowFontScaling" | "ellipsizeMode" | ... 66 more ... | "tvParallaxProperties">'.

38         <ListItem.Chevron color={theme.textStyles.iconPrimary.color} />
            ~~~~~~~~~~~~~~~~

[redacted].tsx:91:8 - error TS2741: Property 'tvParallaxProperties' is missing in type '{ color?: string | number | OpaqueColorValue | undefined; borderRadius?: number | undefined; iconStyle?: TextStyle | undefined; style?: TextStyle | ViewStyle | undefined; ... 71 more ...; brand?: boolean | undefined; }' but required in type 'Pick<IconButtonProps & { type?: string | undefined; Component?: typeof Component | undefined; reverse?: boolean | undefined; raised?: boolean | undefined; containerStyle?: StyleProp<...>; ... 5 more ...; brand?: boolean | undefined; } & Partial<...>, "style" | ... 68 more ... | "tvParallaxProperties">'.

91       <REIcon {...props} />
          ~~~~~~

[redacted].tsx:71:20 - error TS2741: Property 'tvParallaxProperties' is missing in type '{ color: string; }' but required in type 'Pick<Partial<IconProps> & Partial<ThemeProps<Partial<IconProps>>>, "style" | "allowFontScaling" | "ellipsizeMode" | ... 66 more ... | "tvParallaxProperties">'.

71       {chevron && <ListItem.Chevron color={theme.textStyles.iconPrimary.color} />}
                      ~~~~~~~~~~~~~~~~


Found 3 errors.
```

**Comment by kickbk** [comment] 2021-12-01 20:47
There are several unused ts properties throughout this lib. `tvParallaxProperties` is one of them. Possibly leftover props from previous versions that hasn't been cleaned up? Probably need a slight TS update. In the meantime there are several workaround which nine are pretty - add the useless properties to the components you use, or extend the component and add it over there. Another option is to fork the lib and remove those properties.
Personally, I'm hoping the maintainers will clean this up. I'm gonna leave this as is and one day wake up to see these warnings gone :)
Regardless, thumbs up for this awesome library.

**Comment by kickbk** [comment] 2021-12-01 20:50
https://reactnative.dev/docs/touchableopacity#tvparallaxproperties-android
The maintainers will probably need to change these properties to optional in the ts definition files.

**Comment by renchap** [comment] 2021-12-13 15:47
This is a duplicate of #3227.

As [explained in the other issue](https://github.com/react-native-elements/react-native-elements/issues/3227#issuecomment-992608440), this is fixed in the latest git version, you can install `react-native-elements` from git until this is fixed.

**Comment by jkoutavas** [comment] 2022-01-06 00:56
> This is a duplicate of #3227.
> 
> As [explained in the other issue](https://github.com/react-native-elements/react-native-elements/issues/3227#issuecomment-992608440), this is fixed in the latest git version, you can install `react-native-elements` from git until this is fixed.

@renchap, thank you for your info!

FYI, `react-native-elements 4.0.0-beta.0` does indeed fix the initial type errors I was seeing, but, I'm now getting a `Property 'underlayColor' does not exist on type 'IntrinsicAttributes & Omit<PressableProps & { containerStyle?: StyleProp<ViewStyle>; disabledStyle` error on using ListItem's `underlayColor` property:

```ts
    <ListItem
      containerStyle={styles.listItem}
      underlayColor="transparent"
      activeOpacity={0.3}
      onPress={(route || onNavigate) && onNavigationPress}
      {...listItemProps}
    >
```

I'm on React Native 0.66.4

**Closed** 2022-01-30 17:57 UTC
Labels: 📞  Needs Response from Author, 🗂 Types
