### ISSUE TITLE
Draggable Item

### ISSUE THREAD

**Issue by KrisLau** [react-native-elements/react-native-elements#3095] opened 2021-06-22 20:55 UTC
**Is your feature request related to a problem? Please Describe.**
I just noticed that ListItem has a Swipeable component (https://reactnativeelements.com/docs/listitem/#listitem-swipable) and I thought it would also be cool to have the component be draggable to allow for reordering of the list.

**Describe the solution you'd like**
Maybe have a Provider that wraps around a group of components that allows the children to be reordered. Would be cool if it isn't specific to ListItems but that's more like a bonus haha.
![image](https://res.cloudinary.com/flycatcher/image/upload/v1572289775/listgif_igl9j7.gif)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by arpitBhalla** [comment] 2021-06-23 02:17
Duplicate of https://github.com/react-native-elements/react-native-elements-universe/issues/7.

**Closed** 2021-06-23 18:37 UTC
