### ISSUE TITLE
Icon stops showing after upgrading RN to 0.61.1 from 0.59.9

### ISSUE THREAD

**Issue by emclab** [react-native-elements/react-native-elements#2126] opened 2019-10-11 18:44 UTC
Use icon in react-native-elements 1.2.3 in my RN app. 

         import {Icon } from "react-native-elements";

The octicon is used in header:

    const icon_size = 25;
     const EventStack = createStackNavigator({
 
      Event:  {
        screen: EventWithSelf,
        navigationOptions: ({navigation}) => {
          return {
            title: 'Event',
            headerRight: (
              <TouchableOpacity>
                <Icon 
                    name="plus" 
                    size={icon_size} 
                     type='octicon' 
                    reverse={true}
                    onPress={() => navigation.navigate("NewEvent")}
                    />
              </TouchableOpacity>
              ),
         }}
      },

The react-navigation is 4.0.10.

**Explain what you did**
Upgraded react native from 0.59.9 to 0.61.1

**Expected behaviour**
Icon shows

**Describe the bug**
The octicon stops showing. Instead it is only showing a placeholder.

**To Reproduce**
We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

Example:

```bash
# Snack
https://snack.expo.io/xxx

# Steps
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

**Possible Solution**
Can you suggest a possible fix that would address this issue?

**Screenshots**

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |  1.2.3       |
| react-native          |  0.61.1       |
|  yarn           |  1.15.2       |

**Comment by iRoachie** [comment] 2019-10-11 18:49
Duplicate of #2064

**Closed by iRoachie** 2019-10-11 18:49 UTC
