### ISSUE TITLE
New Slider Prop (for double ended slider)

### ISSUE THREAD

**Issue by HariAcidReign** [react-native-elements/react-native-elements#2950] opened 2021-04-08 05:11 UTC
**Is your feature request related to a problem? Please Describe.**

Currently in a slider, the `minimumValue` denotes the value of the lowest possible number choosable and `maximumValue` is the converse. 
What if, I want to create a double-ended slider.  Like this:
https://www.npmjs.com/package/react-native-range-slider

Usecases: Choosing a range of prices to shop (eg. in Amazon mobile app)

**Describe the solution you'd like**

It is pretty straightforward. The current props do not change. But I add 2 new props `selectedMinimum` and `selectedMaximum` that can be modified by 2 RNE `thumbProps` components. These values can lie **ONLY** between the values of  `minimumValue`  and  `maximumValue` 

![image](https://user-images.githubusercontent.com/58134096/113971571-a5ba6e00-9856-11eb-9a72-9b685f3dc11c.png)

**Additional context**

Clearly, this is not a new feature addition, but just an extension of a currently existing feature.
Open to comments and suggestions, and willing to implement them 🙌🏻

**Comment by HariAcidReign** [comment] 2021-04-08 05:12
I'll be modifying the schema in RNE, and implement the demo in RNE-app if the idea is accepted. 🎉

**Comment by flyingcircle** [comment] 2021-04-11 00:02
Duplicate of #15

**Closed by flyingcircle** 2021-04-11 00:02 UTC
