### ISSUE TITLE
react native elements SearchBar

### ISSUE THREAD

**Issue by samuel-Kaminsky** [react-native-elements/react-native-elements#2386] opened 2020-06-07 19:55 UTC
on v-2.0.2

When I try to use SearchBar With the expo I get the error as below: 
Unable to resolve "@expo/vector-icons/Fontisto" from "node_modules/react-native-elements/src/helpers/getIconType.js" 
I also tried to install the react-native-vector-icons and it didn't help.

| software              | version |
| --------------------- | ------- |
| react-native-elements |         |
| react-native-expo          |         |

**Comment by flyingcircle** [comment] 2020-06-08 04:37
Duplicate of #2384

**Closed by flyingcircle** 2020-06-08 04:37 UTC
