### ISSUE TITLE
Picker , react native elements version of Select, Options tag of react

### ISSUE THREAD

**Issue by nihal-37-37** [react-native-elements/react-native-elements#3185] opened 2021-08-27 22:14 UTC
**There is no Good library Picker ( means replacement of Select, Option tag) **
react native elements provide a far better version of every component exist in RN. So I request you to consider Picker kind of Component 

example of what I am trying to say :- 
![resp_-_m](https://user-images.githubusercontent.com/64120673/131193700-b4bde31b-d5c0-4374-a1f1-a9b30bfe92c3.png)

**Comment by flyingcircle** [comment] 2021-08-29 20:32
Duplicate of https://github.com/react-native-elements/react-native-elements-universe/issues/11

**Closed by flyingcircle** 2021-08-29 20:32 UTC
