### ISSUE TITLE
Support for non-light/dark themes.

### ISSUE THREAD

**Issue by rueiwoqp** [react-native-elements/react-native-elements#2795] opened 2021-03-05 18:50 UTC
I'll preface this by saying "If there's a way to accomplish this at the top of the component hierarchy, I don't know what it is".
I'd like to offer more themes to my users. i.e. light/dark/solarized/blue/whatever

It seems that currently only light and dark are supported. e.g. When I use state at the App level to change the theme, it gets merged with the current theme. and so, instead of converting all components to the new theme, it's a mix of the old and new.  This works ok with `useDark` because this tells the ThemeProvider which theme to use as the default, but it's binary. 

I want to have an option to replace the theme at the top level without merging. Eg.
```
  // themesSlice.js
export const selectTheme = createSelector(value => {
  switch (value) {
    case 'dark':
      return DarkTheme;
    case 'blue':
      return BlueTheme;
    case 'auto':
      return deviceColorScheme === 'dark'
        ? DarkTheme
        : DefaultTheme;
    default:
      return DefaultTheme;
  }
});

  // App.js
  const theme = useSelector(state => selectTheme(state, 'blue'));

 ...

  return (
    <ThemeProvider theme={theme} replaceTheme={true}>
    ...
    </ThemeProvider>

  );
```

https://user-images.githubusercontent.com/42003718/110160926-85a01680-7da1-11eb-963c-4e9c000e79e4.mov

**Comment by flyingcircle** [comment] 2021-03-07 20:02
Did you try using `replaceTheme`?  https://reactnativeelements.com/docs/customization#using-the-theme-in-your-own-components 
It is not a bool prop like you are trying to use it as here.

**Comment by flyingcircle** [comment] 2021-03-07 20:05
This also looks like a duplicate of #2754

**Closed by flyingcircle** 2021-03-07 20:05 UTC
