### ISSUE TITLE
Tooltip hovering in wrong position on Android

### ISSUE THREAD

**Issue by sabun123** [react-native-elements/react-native-elements#2180] opened 2019-11-11 04:03 UTC
Hi,

I am using react-native-elements version 1.2.7 and I've run into a snag. The tooltip pop up is correctly placed in iOS but in Android it seems to offshoot itself above it's location. Is there a specific prop or style that needs to be used specifically for Android to fix this? I couldn't find anything about this in the documentation.

**Expected behavior**

The Android version should match the iOS version. The tooltip should be correctly positioned under the button that triggers it to appear.

**Describe the bug**

The tooltip is appearing in the wrong location on Android. It appears above the pressable button, rather than below it.

**Screenshots**

On iOS it works just right:
![Screenshot 2019-11-11 at 11 55 57 AM](https://user-images.githubusercontent.com/3523483/68560038-40542900-047a-11ea-85f3-4d66fb3e5212.png)

On Android, exact same setup, it bugs out:
![Screenshot 2019-11-11 at 11 56 04 AM](https://user-images.githubusercontent.com/3523483/68560042-48ac6400-047a-11ea-9c74-74fcf5de899e.png)

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   1.2.7      |
| react-native          |   0.60.5      |

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 18.21 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5
```

**Comment by iRoachie** [comment] 2019-11-11 15:58
Duplicate of https://github.com/react-native-elements/react-native-elements/issues/1871/

Fixed by https://github.com/react-native-elements/react-native-elements/commit/85849176ec82e4f036c0df2a0837ba9038e3cea2. Will be available next major release.

**Closed by iRoachie** 2019-11-11 15:58 UTC
Labels: :boom:  Bug, ✅ Fixed - Next Release

**Comment by sabun123** [comment] 2019-11-12 04:06
Thanks iRoachie!

In the meantime, I just set my version of react-native-elements to that specific commit in package.json to fix my issue.

```
"react-native-elements": "https://github.com/react-native-elements/react-native-elements#8584917",
```

And then used the new prop that commit provides in the tooltip component:
```
skipAndroidStatusBar={true}
```

It works on Android as expected now.

**Comment by baicuhaha** [comment] 2019-11-26 08:30
When will the new version be updated

**Comment by Ashutosh-Tiwari** [comment] 2022-02-18 06:07
https://github.com/react-native-elements/react-native-elements/issues/1871
The issue still remains. When the Modal is not used, the skipAndroidStatusBar makes no difference.
