### ISSUE TITLE
Input element left icon displaced in android

### ISSUE THREAD

**Issue by azizulhaq800804** [react-native-elements/react-native-elements#2203] opened 2019-12-05 05:32 UTC
I am using react native input elements and font awesome in an expo project. Here is my code snippet,

import { Input, Text } from 'react-native-elements';
import Icon from 'react-native-vector-icons/FontAwesome';

<Input autoFocus
              ref={(input) => { this.email = input; }}
              placeholder='Name'
              leftIcon={{ type: 'font-awesome', name: 'hospital-o'}}
              onChangeText={(text)=>this.handleChangeText({name:text})}
              value={this.state.name}
              name="name"
            />

However, left icon is displaced by a small marging inside the input element. Screen shot attached,

![Screenshot_2019-12-05_110206](https://user-images.githubusercontent.com/58458031/70206787-d9f9b800-1752-11ea-8877-64a85ad89a80.jpg)

**Comment by Qiyu8** [comment] 2019-12-05 08:04
in order to fix this issue, You can pass leftIconContainerStyle attribute to input.  Inside input left Icon, there has a default "marginLeft: 15" style.

**Comment by flyingcircle** [comment] 2020-04-27 17:58
Duplicate of #1962 , and fixed for 2.0.0

**Closed by flyingcircle** 2020-04-27 17:58 UTC
