### ISSUE TITLE
 Letter Avatar throws: WARN  ReactImageView: Image source "null" doesn't exist

### ISSUE THREAD

**Issue by carl-sauter** [react-native-elements/react-native-elements#3742] opened 2023-01-27 11:09 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Explain what you did

Using a Letter Avatar: <Avatar containerStyle={styles.drawerHeaderAvatar} rounded size={90} title="CS"/>

### Expected behavior

Not throwing a warning

### Describe the bug

Always logs:  WARN  ReactImageView: Image source "null" doesn't exist

### Steps To Reproduce

```Markdown
Use: <Avatar rounded size={90} title="CS"/>
```

### Your Environment

React Native Elements Env Info
                              
## Global Dependencies:       
                              
   No related dependency found
                              
## Local Dependencies:        
                              
 - @rneui/base : ^4.0.0-rc.7  
 - @rneui/themed : ^4.0.0-rc.7
 - react-native : 0.71.1      
 - @types/react : ^18.0.27

**Comment by linusrush** [comment] 2023-01-31 10:44
Same issue here. Ever since i upgraded to react-native 0.71. this warning keeps appearing

**Comment by Kelvin-Lim-PKM** [comment] 2023-02-01 07:04
Same issue here.

**Comment by gsolorzanob** [comment] 2023-02-10 17:44
Same issue here.

**Comment by khushal87** [comment] 2023-03-04 18:20
I was able to triage this issue and will soon raise a fix for it. Thanks 😄

**Comment by ChromeQ** [comment] 2023-03-05 01:56
Same thing going on here since expo upgrade to v48 which includes react-native 0.71.x.
And also is happening to Avatar with `icon` prop not just title

**Comment by Bilal-Abdeen** [comment] 2023-03-08 21:39
Every time the screen is displayed, I get the same error described in this issue. In addition to that, on the very 1st render of the screen, I get the following error message. I am not sure if they are related. 

@khushal87 Thank you for the PR. I cannot wait for it to be merged. 

```node
Warning: Failed prop type: Invalid props.style key `borderStyle` supplied to `Image`.
Bad object: {
  "position": "absolute",
  "left": 0,
  "right": 0,
  "top": 0,
  "bottom": 0,
  "flex": 1,
  "borderWidth": 5,
  "borderStyle": "solid",
  "borderColor": "transparent"
}
Valid keys: [
  "alignContent",
  "alignItems",
  "alignSelf",
  "aspectRatio",
  "borderBottomWidth",
  "borderEndWidth",
  "borderLeftWidth",
  "borderRightWidth",
  "borderStartWidth",
  "borderTopWidth",
  "borderWidth",
  "bottom",
  "columnGap",
  "direction",
  "display",
  "end",
  "flex",
  "flexBasis",
  "flexDirection",
  "flexGrow",
  "flexShrink",
  "flexWrap",
  "gap",
  "height",
  "justifyContent",
  "left",
  "margin",
  "marginBlock",
  "marginBlockEnd",
  "marginBlockStart",
  "marginBottom",
  "marginEnd",
  "marginHorizontal",
  "marginInline",
  "marginInlineEnd",
  "marginInlineStart",
  "marginLeft",
  "marginRight",
  "marginStart",
  "marginTop",
  "marginVertical",
  "maxHeight",
  "maxWidth",
  "minHeight",
  "minWidth",
  "overflow",
  "padding",
  "paddingBlock",
  "paddingBlockEnd",
  "paddingBlockStart",
  "paddingBottom",
  "paddingEnd",
  "paddingHorizontal",
  "paddingInline",
  "paddingInlineEnd",
  "paddingInlineStart",
  "paddingLeft",
  "paddingRight",
  "paddingStart",
  "paddingTop",
  "paddingVertical",
  "position",
  "right",
  "rowGap",
  "start",
  "top",
  "width",
  "zIndex",
  "shadowColor",
  "shadowOffset",
  "shadowOpacity",
  "shadowRadius",
  "transform",
  "backfaceVisibility",
  "backgroundColor",
  "borderBottomLeftRadius",
  "borderBottomRightRadius",
  "borderColor",
  "borderRadius",
  "borderTopLeftRadius",
  "borderTopRightRadius",
  "objectFit",
  "opacity",
  "overlayColor",
  "tintColor",
  "resizeMode"
]
    at BaseImage (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.casualjob&modulesOnly=false&runModule=true:60367:106)
    in Image (created by Avatar)
    in RCTView (created by View)
    in View (created by Avatar)
    in Avatar
    in Themed.Avatar (created by CellRenderer)
    in RCTView (created by View)
    in View (created by PadView)
    in PadView (created by ListItem)
    in RCTView (created by View)
    in View (created by Pressable)
    in Pressable (created by Pressable)
    in ListItem
    in Themed.ListItem (created by CellRenderer)
    in RCTView (created by View)
    in View (created by CellRenderer)
    in VirtualizedListCellContextProvider (created by CellRenderer)
    in CellRenderer (created by VirtualizedList)
    in RCTView (created by View)
    in View (created by ScrollView)
    in RCTScrollView (created by ScrollView)
    in AndroidSwipeRefreshLayout (created by RefreshControl)
    in RefreshControl (created by VirtualizedList)
    in ScrollView (created by ScrollView)
    in ScrollView (created by VirtualizedList)
    in VirtualizedListContextProvider (created by VirtualizedList)
    in VirtualizedList (created by FlatList)
    in FlatList (created by ItemList)
    in RCTView (created by View)
    in View (created by ItemList)
    in ItemList (created by ListRosterEmployerScreen)
    in RCTView (created by View)
    in View (created by ListRosterEmployerScreen)
    in ListRosterEmployerScreen (created by Connect(ListRosterEmployerScreen))
    in Connect(ListRosterEmployerScreen) (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RCTView (created by View)
    in View (created by SceneView)
    in RNSScreen (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by ScreenStack)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator (created by SingleStack)
    in SingleStack (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by DrawerView)
    in RCTView (created by View)
    in View (created by Screen)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by Screen)
    in Screen (created by DrawerView)
    in RNSScreen (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by DrawerView)
    in RNSScreenContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by DrawerView)
    in RCTView (created by View)
    in View (created by DrawerView)
    in RCTView (created by View)
    in View (created by AnimatedComponent(View))
    in AnimatedComponent(View)
    in Unknown (created by DrawerView)
    in RCTView (created by View)
    in View (created by AnimatedComponent(View))
    in AnimatedComponent(View)
    in Unknown (created by PanGestureHandler)
    in PanGestureHandler (created by PanGestureHandler)
    in PanGestureHandler (created by DrawerView)
    in DrawerView (created by DrawerViewBase)
    in DrawerViewBase (created by DrawerView)
    in RNGestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by DrawerView)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by DrawerView)
    in DrawerView (created by DrawerNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by DrawerNavigator)
    in DrawerNavigator (created by MainMenuSingleStack)
    in MainMenuSingleStack (created by Navigation)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by Navigation)
    in Navigation (created by Connect(Navigation))
    in Connect(Navigation) (created by App)
    in ThemeProvider (created by App)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by App)
    in PersistGate (created by App)
    in Provider (created by App)
    in App (created by HeadlessCheck)
    in HeadlessCheck
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in casualjob(RootComponent)
```

**Comment by echarbeto** [comment] 2023-04-10 00:46
I can confirm that the same thing happens to me when an Avatar with an icon is rendered in my case for the time being.

Package.json
`"@rneui/themed": "^4.0.0-rc.7"
"expo": "~48.0.10",
"react-native": "0.71.6",
"react-native-safe-area-context": "4.5.0",
"react": "18.2.0",`

**Comment by mednche** [comment] 2023-05-14 12:58
Same issue (on android only) since upgrading to react native 0.71.8.

**Comment by francois-spectre** [comment] 2023-06-01 11:58
same issue here

**Closed as completed** 2023-06-07 07:08 UTC
Labels: component: Avatar

**Comment by xpt300** [comment] 2023-06-12 09:09
Same here

**Comment by joshua-natividad** [comment] 2023-06-14 16:51
Same here, any idea when the fix will be released?

**Comment by laurielabergepetalmd** [comment] 2023-06-28 20:43
Same issue here

**Comment by sdancer75** [comment] 2023-07-07 12:24
same problem here

**Comment by pablolucio97** [comment] 2023-07-08 10:05
Same here. There's an approach to check if the URL is empty but it doesn't works to.

**Comment by augini** [comment] 2023-07-10 16:40
I have been experiencing the same issue where the value `undefined` of the source triggers the warning message.

**Comment by ChromeQ** [comment] 2023-07-11 07:35
This is marked as complete over a month now, any timeline on releasing next branch @arpitBhalla ? Thanks

**Comment by emmsdan** [comment] 2023-07-27 08:41
> I was able to triage this issue and will soon raise a fix for it. Thanks 😄

@khushal87 when should we look forward to the fix?

**Comment by bernborgess** [comment] 2023-08-04 14:27
Any development so far? What version will have the fix?

**Comment by Bilal-Abdeen** [comment] 2023-08-05 23:23
@bernborgess The fix for this has been included in [v4.0.0-rc.8](https://github.com/react-native-elements/react-native-elements/releases/tag/v4.0.0-rc.8)

**Comment by nishadadilshan** [comment] 2023-08-09 08:02
> Same issue here. Ever since i upgraded to react-native 0.71. this warning keeps appearing

I also facing this issue after update the RN version

**Comment by sdancer75** [comment] 2023-08-21 06:32
> The fix for this has been included in [v4.0.0-rc.8](https://github.com/react-native-elements/react-native-elements/releases/tag/v4.0.0-rc.8)

update to v4.0.0-rc.8 (https://github.com/react-native-elements/react-native-elements/releases/tag/v4.0.0-rc.8)

**Comment by haeniya** [comment] 2023-08-21 17:38
Are you guys able to update to the latest version?

Trying to install version 4.0.0-rc.8 of @rneui/base and @rneui/themed results in the following error for me:
```
npm ERR! Found: @rneui/base@4.0.0-rc.8
npm ERR! node_modules/@rneui/base
npm ERR!   @rneui/base@"^4.0.0-rc.8" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @rneui/base@"4.0.0-rc.7" from @rneui/themed@4.0.0-rc.8
npm ERR! node_modules/@rneui/themed
npm ERR!   @rneui/themed@"4.0.0-rc.8" from the root project
```
Looks like @rneui/themed@4.0.0-rc.8 still has a dependency on @rneui/base@"4.0.0-rc.7. Not sure if that's on purpose or what's the reason behind it. Did anyone had the same issue?

**Comment by Bilal-Abdeen** [comment] 2023-08-22 00:39
@haeniya I am not sure how to fix the specific error you got. However, it can help to uninstall the old version; then, install the new one. If this did not work, you can try the following steps (on Windows) or similar commands on Mac. 
```
npm start -- --reset-cache
npm uninstall @rneui/base @rneui/themed
rd /q /s node_modules
npm install
npm install @rneui/base @rneui/themed
```

**Comment by haeniya** [comment] 2023-08-22 17:40
Thanks for the response @Bilal-Abdeen.
Uninstalling and installing again result in the following versions:

```
@rneui/base: 4.0.0-rc.7
@rneui/themed: 4.0.0-rc.8
```

Looking at the code there is a peer dependency defined on @rneui/themed to @rneui/base@4.0.0-rc.7. See here: https://github.com/react-native-elements/react-native-elements/blob/next/packages/themed/package.json#L53
No idea if that's intended or not.

**Comment by Bilal-Abdeen** [comment] 2023-08-22 22:58
@haeniya I uninstalled both (base & theme.) Then, I installed both. It worked for me.

**Comment by Bilal-Abdeen** [comment] 2023-08-24 04:27
@haeniya It seems that other people are having dependency error #3829

**Comment by JurieSpies** [comment] 2023-11-17 07:37
My fix for this:

```js
<Avatar
      rounded
      size={size}
      title={initials}
      containerStyle={containerStyle}
      titleStyle={titleStyle}
      source={{ uri: 'https://' }} //added to remove ReactImageView: Image source "null" doesn't exist
      placeholderStyle={{ backgroundColor: 'transparent' }} //to remove grey background
    />

**Comment by tlmader** [comment] 2023-12-01 17:12
What is the proper way to use the placeholder content before the URI is available? @JurieSpies 's solution prevents the warning, but it doesn't seem ideal.

**Comment by justinhandley** [comment] 2024-02-05 19:50
Did anyone ever find a less hacky solution to this one?

**Comment by MickaelAustoni** [comment] 2024-03-05 13:31
The fix proposed by @JurieSpies  `source={{ uri: 'https://' }}` is not the best because this make memory leak caused by empty queries on iOS

![ios](https://github.com/react-native-elements/react-native-elements/assets/108873902/c1fb602f-eabf-4323-961a-0bfc6814eeb4)

Instead as quick fix you can  `source={{ uri: "data:image/png" }}` for fix error `ReactImageView: Image source "null" doesn't exist` :
```ts
<Avatar
  rounded
  size={size}
  title={initials}
  containerStyle={containerStyle}
  titleStyle={titleStyle}
  source={{ uri: "data:image/png" }} // Added to remove ReactImageView: Image source "null" doesn't exist
  placeholderStyle={{ backgroundColor: 'transparent' }} // Remove grey background
/>
```

or in your theme like this :

```ts
const theme = createTheme({
  components: {
    Avatar: () => ({
      placeholderStyle: {
        backgroundColor: "transparent",
      },
      source: {
        uri: "data:image/png",
      },
    }),
  },
});
```

Tested on `4.0.0-rc.7`

**Comment by Slicefresh22** [comment] 2024-03-20 23:55
My fix: 

```javascript
      <Avatar
          rounded={rounded}
          size={size ?? 24}
         { ...(title && !source ? { title } : {}) }
         { ...(source ? {source: { uri: source }} : {}) }
      />
```

**Comment by nabzmohd** [comment] 2024-04-30 10:28
> ```js
>     source={{ uri: 'https://' }} //added to remove ReactImageView: Image source "null" doesn't exist
>       placeholderStyle={{ backgroundColor: 'transparent' }} //to remove grey background
> ```

This work for me 
    source={{ uri: 'https://' }} //added to remove ReactImageView: Image source "null" doesn't exist
      placeholderStyle={{ backgroundColor: 'transparent' }} //to remove grey background

Thanks

**Comment by augini** [comment] 2024-05-13 21:03
> > ```js
> >     source={{ uri: 'https://' }} //added to remove ReactImageView: Image source "null" doesn't exist
> >       placeholderStyle={{ backgroundColor: 'transparent' }} //to remove grey background
> > ```
> 
> This work for me source={{ uri: 'https://' }} //added to remove ReactImageView: Image source "null" doesn't exist placeholderStyle={{ backgroundColor: 'transparent' }} //to remove grey background
> 
> Thanks

I think it resolved it for me.

**Comment by abbasiArbisoft** [comment] 2024-10-29 12:13
The problem with above approach is `containerStyle={{ backgroundColor:'red'  }}` wouldn't work.
Another workaround is add this in props `ImageComponent={() => null}`
