### ISSUE TITLE
Button component error - `TypeError: Cannot convert undefined value to object`

### ISSUE THREAD

**Issue by korifey91** [react-native-elements/react-native-elements#3530] opened 2022-05-17 16:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

Just to use `Button` component

### Expected behavior

It should work

### Describe the bug

Using Button component crashes with error, even without any props

The error: 
`TypeError: Cannot convert undefined value to object`
```
This error is located at:
    in Button
    in Themed.Button 
```

### Steps To Reproduce

```Markdown
You can see an error even in the demo snack - https://reactnativeelements.com/docs/components/button

But the error says there - `undefined is not an object (evaluating 'te.spacing[M]')`
```

### Your Environment

<details>
<summary>`npx @rneui/envinfo`</summary>
```

System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 116.81 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.8.0 - ~/.nvm/versions/node/v16.8.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 7.21.0 - ~/.nvm/versions/node/v16.8.0/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    Homebrew: 3.4.11 - /opt/homebrew/bin/brew
    pip3: 20.2.3 - /usr/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 13.1.6 - /usr/bin/gcc
    Git: 2.32.0 - /usr/bin/git
    Clang: 13.1.6 - /usr/bin/clang
  Servers:
    Apache: 2.4.51 - /usr/sbin/apachectl
  Virtualization:
    Docker: 20.10.12 - /usr/local/bin/docker
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
  IDEs:
    Nano: 2.0.6 - /usr/bin/nano
    Vim: 8.2 - /usr/bin/vim
    WebStorm: 2022.1
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Perl: 5.30.3 - /usr/bin/perl
    Python: 2.7.18 - /usr/bin/python
    Python3: 3.8.9 - /usr/bin/python3
    Ruby: 2.6.8 - /usr/bin/ruby
  Databases:
    PostgreSQL: 14.3 - /opt/homebrew/bin/postgres
    SQLite: 3.36.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 101.0.4951.64
    Safari: 15.2

```
</details>

**Comment by arpitBhalla** [comment] 2022-05-17 17:01
Duplicate of #3519

**Comment by arpitBhalla** [comment] 2022-05-17 17:01
This change will be available in next release. You can try this, by installing [Bleeding Edge](https://reactnativeelements.com/docs/next/installation#bleeding-edge) version

or you can try with expo template
```bash
expo init app --template @rneui/template@bleeding-edge
```

**Closed as completed by arpitBhalla** 2022-05-17 17:01 UTC
Labels: component: Button

**Comment by sovetski** [comment] 2022-05-28 14:03
> This change will be available in next release. You can try this, by installing [Bleeding Edge](https://reactnativeelements.com/docs/next/installation#bleeding-edge) version
> 
> or you can try with expo template
> 
> ```shell
> expo init app --template @rneui/template@bleeding-edge
> ```

What is the "Bleeding Edge" version? Do we have a lot of difference with the latest version with that?

**Comment by sovetski** [comment] 2022-05-28 14:20
I have the same problem and actually it is very strange, each code we copy from the latest documentation does not work

**Comment by arpitBhalla** [comment] 2022-05-28 17:18
Hey @sovetski which version are you using?

**Comment by sovetski** [comment] 2022-05-28 18:30
> Hey @sovetski which version are you using?

Hi, the latest version [4.0.0-rc.4](https://reactnativeelements.com/docs)

**Comment by arpitBhalla** [comment] 2022-05-31 05:27
@sovetski Could you provide snack/snippet of code and the docs which you are referring.
