### ISSUE TITLE
Slack Down

### ISSUE THREAD

**Issue by rambleraptor** [react-native-elements/react-native-elements#3060] opened 2021-05-28 18:35 UTC
It appears that the React Native Elements Slack is down. It's just getting a Heroku error.

**Explain what you did (Required)**
Went to https://react-native-elements-slack.herokuapp.com/

Access the Slack.
**Expected behavior (Required)**

Receive an invite to join the Slack channel.

**Describe the bug (Required)**

**To Reproduce (Required)**

We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

**Screenshots (Required)**

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |         |
| react-native          |         |

**Comment by khushal87** [comment] 2021-05-30 14:32
@rambleraptor If the issue is resolved in #3061 please mark it as close too. Thank you.

**Comment by flyingcircle** [comment] 2021-06-04 14:44
I don't see any error. Slack is working as far as I see.

**Closed by flyingcircle** 2021-06-04 14:44 UTC
