### ISSUE TITLE
can't upgrade react-native-safe-area-context when using react-native-elements

### ISSUE THREAD

**Issue by VanHuynh1997** [react-native-elements/react-native-elements#3715] opened 2022-12-23 03:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

I'm using react-native-elements: ^3.4.2, I can't upgrade react-native-safe-area-context
react-native-elements: ^3.4.2 compatible only with  react-native-safe-area-context: 3.1.9

### Expected behavior

I want to upgrade the latest version react-native-safe-area-context not error

### Describe the bug

When i upgrade the lastest version react-native-safe-area-context
Android and IOS alert error

### Steps To Reproduce

```Markdown
Go to terminal write command: npm i react-native-safe-area-context
After build project on android and ios alert error dependencies on react-native-elements
```

### Your Environment

<details>
<summary>`npx @rneui/envinfo`</summary>

      ```
        Output from `npx @rneui/envinfo` goes here.
      ```

</details>

**Comment by andreieuganox** [comment] 2022-12-23 19:34
Error

```
code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: QApp@0.0.1
npm ERR! Found: react-native-safe-area-context@4.4.1
npm ERR! node_modules/react-native-safe-area-context
npm ERR!   react-native-safe-area-context@"^4.4.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native-safe-area-context@"^3.1.9" from react-native-elements@3.4.2
npm ERR! node_modules/react-native-elements
npm ERR!   react-native-elements@"^3.4.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/andrei.popov/.npm/eresolve-report.txt for a full report.
```

**Comment by arpitBhalla** [comment] 2022-12-23 20:16
Try installing `react-native-elements@3.4.3`

**Comment by arpitBhalla** [comment] 2022-12-27 19:37
Duplicate of #3697

**Closed as completed by arpitBhalla** 2022-12-27 19:37 UTC
Labels: Needs Triage
