### ISSUE TITLE
Android individual star images are not showing. Instead they are coming in as a single bar.

### ISSUE THREAD

**Issue by oporter1** [react-native-elements/react-native-elements#2630] opened 2020-10-06 21:23 UTC
**Explain what you did (Required)**
I implemented react-native-ratings in my react native app. It is working as expected on iOs but on Android the star images are not displaying as separate images. Rather it is coming in as a single bar with variants in its length. 

display the google star ratings on an andriod

**Expected behavior (Required)**
the star images to be visible and separated. 

the star images to be visible and separated. 

**Describe the bug (Required)**
when looking at a map with the react-native-ratings implemented in android, you can click on a pin on the map and what I chose to display is the name of the place, the star ratings, and the type of place it is. What is actually displayed is the name of the place, a rectangle yellow bar that is the length of the "star ratings", and the type of place it is.

**To Reproduce (Required)**

We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

           
              `class CustomCallout extends React.Component {
                render() {
                  return (
                    <View style={[styles.container, this.props.style]}>
                      <View style={styles.bubble}>
                        <View style={styles.amount}>{this.props.children}</View>
                      </View>
                      <View style={styles.arrowBorder} />
                      <View style={styles.arrow} />
                    </View>
                  );
                }
              }

               <CustomCallout>
                          <Text style={{fontFamily: Font.Bold}}>
                            {marker.placeName}
                          </Text>
                          <Rating
                            imageSize={15}
                            readonly
                            startingValue={marker.rating}
                            style={{marginLeft: -35}}
                          />
                          <Text style={{fontFamily: Font.Regular}}>
                            {marker.placeType}
                          </Text>
                        </CustomCallout>`

**Screenshots (Required)**

<img width="507" alt="starthing" src="https://user-images.githubusercontent.com/12777243/95261534-8fc0e780-07f8-11eb-860b-b2e4e07d8d95.png">

**Your Environment (Required):**

| software    android          | version | react-native: 0.61.4
| --------------------- | ------- |
| react-native-elements |   Rating      |
| react-native          |         |

**Comment by pranshuchittora** [comment] 2020-10-11 21:43
Hi @oporter1 I tried running the above-mentioned code and unfortunately I am not able to reproduce the following issue.
Here's the snack demo -> https://snack.expo.io/9w6aU8DQ8

**Comment by flyingcircle** [comment] 2020-10-17 16:14
Closing due to in ability to reproduce

**Closed by flyingcircle** 2020-10-17 16:14 UTC
Labels: 📞 Needs Response from Author

**Comment by junqdu** [comment] 2021-05-27 09:10
@oporter1 were you able to resolve it?

**Comment by thenderson55** [comment] 2022-05-19 03:18
Same issue with iOS now.

**Comment by arpitBhalla** [comment] 2022-05-19 03:36
Try reporting this on react-native-ratings repo?
