### ISSUE TITLE
Image not showed after update to 3.4.0

### ISSUE THREAD

**Issue by GaylordP** [react-native-elements/react-native-elements#2991] opened 2021-04-23 17:49 UTC
I just updated my project using `npm update`. `react-native-elements` updated from `3.3.2` to `3.4.0`

But now my images don't show up anymore.

I am very surprised because my situation is really very simple : 

    import {
      Image,
    } from 'react-native-elements'

    const ResponsiveImage = () => {
      return (
        <Image
          source={{ uri: 'http://....' }}
          style={[
            {
              width: 500,
              height: 200,
            },
          ]}
        />
      )
    }

As you can see my situation is very simple but the image is not showing. But when I import from the React Native library, my image displays fine :

    import { Image } from 'react-native'

| software              | version |
| --------------------- | ------- |
| react-native-elements | 3.4.0 |
| react-native          | 0.64.0 |

**Comment by kylemarimon** [comment] 2021-04-23 19:46
I'm having the same issue.

**Comment by karimatwa** [comment] 2021-04-25 00:32
same issue.

**Comment by flyingcircle** [comment] 2021-04-25 17:49
Duplicate of #2992 and fixed in 3.4.1

**Closed by flyingcircle** 2021-04-25 17:49 UTC

**Comment by kylemarimon** [comment] 2021-04-25 18:06
Thanks all!
