### ISSUE TITLE
Header Jumping

### ISSUE THREAD

**Issue by nica0012** [react-native-elements/react-native-elements#3252] opened 2021-11-20 16:45 UTC
Ever since 3.4.2, when navigating from a screen with **React Native Router Flux** header to a screen with **RNE** header, the RNE **header jumps every-time on load**. It did not do this before.

Anyone experiencing this?

**Comment by arpitBhalla** [comment] 2022-04-02 13:01
Duplicate of #3433

**Closed by arpitBhalla** 2022-04-02 13:01 UTC
Labels: component: Header, package: base

**Comment by amonam** [comment] 2022-04-15 14:00
It happens for me.
