### ISSUE TITLE
React Native Web, Icon: loads all icons

### ISSUE THREAD

**Issue by tamis-laan** [react-native-elements/react-native-elements#3455] opened 2022-04-11 16:29 UTC
When using:
`<Icon name='person' type='material-community'/>`

All icons are packaged with the app, i.e. `MaterialCommunityIcons.ttf` of 405.5 KB is included. This is kind of excessive for one single icon. 

Based on the name and type a single icon should be included, preferably as inlined SVG.

**Comment by arpitBhalla** [comment] 2022-04-29 20:21
Duplicate of #3119

**Closed as completed by arpitBhalla** 2022-04-29 20:21 UTC
Labels: component: Icon, Platform: Web
