### ISSUE TITLE
Header height based on Orientation

### ISSUE THREAD

**Issue by kumaresan-cgvak** [react-native-elements/react-native-elements#1791] opened 2019-02-19 11:32 UTC
**Is your feature request related to a problem? Please Describe.**
Header height is not changed according to the orientation of mobile device. So, header occupies more space in landscape mode.

**Describe the solution you'd like**
Header height can be reduced in Landscape mode of a mobile device.

**Comment by dquessenberry** [comment] 2020-08-04 20:22
Not sure why this issue was closed as it is a legit problem. I am able to reproduce the issue and I've looked through the Header source code, and it does not resize the header height for "notched" iPhones appropriately on orientation change. If the app is refreshed in landscape it does render the Header height appropriately, so I assume the Header component just needs an orientation change listener and to resize the height accordingly from portrait to landscape and vice versa.

In the meantime, I am writing a wrapper component to handle this, but it would be nice if the Header component did this automatically.

**Comment by flyingcircle** [comment] 2020-08-04 20:37
@dquessenberry please feel free to open a PR to fix this.

**Comment by flyingcircle** [comment] 2020-12-14 05:23
It looks like it's not an easy problem to solve. Might have to wait on a `react-native-status-bar-height` v3 https://github.com/ovr/react-native-status-bar-height/issues/13

**Closed** 2020-12-16 22:32 UTC
Labels: Blocked, Header, ✨Enhancement
