### ISSUE TITLE
"react-native-elements 3.0.0-alpha.1" not showing icon "react-native-vector-icons 7.1.0"

### ISSUE THREAD

**Issue by sunilnirania98** [react-native-elements/react-native-elements#2677] opened 2020-11-11 06:48 UTC
I using latest version these versions:
react native 0.63.3
react-native-elements 3.0.0-alpha.1
react-native-vector-icons 7.1.0

i not understand what the actual issue. i try to clear every thing and try many times.
a icon code smaple is:
<Icon name='email-outline' type='material-community' />
<Icon name='key-outline' type='material-community' />
<Icon name='google' type='font-awesome' />
<Icon name='facebook' type='material-community' />

![1605077182465](https://user-images.githubusercontent.com/70876826/98778055-c8ffff00-2417-11eb-85cb-5166292dbd35.JPEG)

**Comment by sunilnirania98** [comment] 2020-11-11 06:49
i using icon as this:-
<Icon name='email-outline' type='material-community' />

**Comment by sunilnirania98** [comment] 2020-11-11 06:53
sample :-
`<Icon name='google' type='font-awesome' /><Icon name='key-outline' type='material-community' />`

**Comment by pranshuchittora** [comment] 2020-11-11 13:22
> sample :-
> `<Icon name='google' type='font-awesome' /><Icon name='key-outline' type='material-community' />`

Hi @sunilnirania98 I am able to reproduce the same. The issue is on the React Native side, but not to worry this can be fixed by manually linking the vector-icons. 

Run `react-native link react-native-vector-icons` and this will fix the issue :) 

Hope it helps. Closing this for now, feel free to reopen this again.
Happy Hacking

**Closed by pranshuchittora** 2020-11-11 13:22 UTC
